### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by KimBitrus26** [hngi/jl-python-mycustomer#10]
**What Functionality / Service / Endpoint would you like to add?**
A short statement

**Describe this Functionality / Service / Endpoint**
A clear and concise description of what you want to add.
This will provide  custom error status from the API
**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?
Yes
**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature. 

**Slack username**
Please include your slack username here
@Kim 
**Additional context**

**Comment by austitech** [comment]
This issue needs clarification from creator.

**Comment by cAtaman** [comment]
I am closing this issue due to lack of clarification
