### ISSUE TITLE
Write a comprehensive README for this project

### ISSUE THREAD

**Issue by cAtaman** [hngi/jl-python-mycustomer#122]
## Complete this section

**What Functionality / Service / Endpoint would you like to add?**
Write a README

**Describe this Functionality / Service / Endpoint**
README should contain every necessary information including:
  - setup instructions
  - running tests
  - a link to CONTRIBUTE.md

**Duplicate prevention**
No duplicate

**Slack username**
Please include your slack username in a comment below

**Comment by judahsemi** [comment]
@Judah
