### ISSUE TITLE
Implement Transaction Model

### ISSUE THREAD

**Issue by iameo** [hngi/jl-python-mycustomer#14]
**What Functionality / Service / Endpoint would you like to add?**
The transaction model for handling models

**Describe this Functionality / Service / Endpoint**
A model to allow for CRUD operations

- Create a Transaction class in transaction.py (models)
- Define fields/attributes in Transaction class
- Transaction class can now be imported when needed to query the database using ORM.

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?

**Slack username**
**@OEmmanuel**

**Additional context**

**Comment by iameo** [comment]
I'm already on this.

**Comment by cAtaman** [comment]
Could you give a more clear description
