### ISSUE TITLE
Register, Login&logout authentication 

### ISSUE THREAD

**Issue by horlamiedea** [hngi/jl-python-mycustomer#15]
**What Functionality / Service / Endpoint would you like to add?**
A short statement

**Describe this Functionality / Service / Endpoint**
A clear and concise description of what you want to add.

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature. 

**Slack username**
Please include your slack username here

**Additional context**

**Comment by horlamiedea** [comment]
I’d write the codes for these auth and add more when I’m done with this

**Comment by cAtaman** [comment]
How's this going @horlamiedea

**Comment by horlamiedea** [comment]
You’d get a reply by 2pm today.
