### ISSUE TITLE
Feature: Create new user

### ISSUE THREAD

**Issue by austitech** [hngi/jl-python-mycustomer#16]
**What Functionality / Service / Endpoint would you like to add?**
Create and persist a new user.

**Describe this Functionality / Service / Endpoint**
Endpoint to add a new user to the database

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?
None

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature. 

**Slack username**
Please include your slack username here
@Austino

**Additional context**

**Comment by aeesha-T** [comment]
Can I have this?

**Comment by austitech** [comment]
yes.. if you do not have any right now.

**Comment by cAtaman** [comment]
This feature had been implemented in #42
