### ISSUE TITLE
Create API specifications for project

### ISSUE THREAD

**Issue by cAtaman** [hngi/jl-python-mycustomer#2]
**What Functionality / Service / Endpoint would you like to add?**
A central specification for all the API endpoints in MyCustomer

**Describe this Functionality / Service / Endpoint**
OpenAPI v2 compliant API specification for all the endpoints for MyCustomer

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?
Yes

**Describe how to intend to go about adding this feature**
I'll be using the `connexion` module available on PyPI. This module allow for api documentation even before development.

**Slack username**
@Ataman

**Additional context**

**Comment by Ataman** [comment]
Yes I totally concur, nice work! ~Ataman

**Comment by cAtaman** [comment]
Haha what are the chances! 

Hi @Ataman. How goes it from your side of the world

**Comment by Ataman** [comment]
@cAtaman 
All fine, just a bit of spam lately due to mentions in Github. I'd suggest to remove the @ in front of the Slack username or changing your repository into a private one. If the mentions continue I might feel compelled to respond to them with, probably useless, commentary.

**Comment by cAtaman** [comment]
Will do

**Comment by Ataman** [comment]
Thank you!
