### ISSUE TITLE
Implement complaint model

### ISSUE THREAD

**Issue by onshimiye** [hngi/jl-python-mycustomer#20]
**What Functionality / Service / Endpoint would you like to add?**
Database schema model for complaints

**Describe this Functionality / Service / Endpoint**
A clear and concise description of what you want to add.

**Duplicate prevention**
It is not being implemented by anyone

**Describe how to intend to go about adding this feature**
Creating a class with necessary fields for a complaint

**Slack username**
@onshimiye

**Additional context**

**Comment by cAtaman** [comment]
Please properly describe the feature you want to work on
