### ISSUE TITLE
Impliment CALL ENDPOINTS  -UPDATE

### ISSUE THREAD

**Issue by Zahira11** [hngi/jl-python-mycustomer#22]
**What Functionality / Service / Endpoint would you like to add?**
A short statement

**Describe this Functionality / Service / Endpoint**
A clear and concise description of what you want to add.

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature. 

**Slack username**
@Zahira

**Comment by Zahira11** [comment]
Working on Call a customer's number.

**Comment by cAtaman** [comment]
Hey @Zahira11 

The specs for call enpoint is 

/call/{customerId}:

consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "customerId"
        in: "path"
        description: "Customer id to call"
       required: true
        type: "integer"
        format: "int64"
     - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: "object"
          required:
          - "number"
          properties:
            number:
              type: "string"
              example: "+23480000000"
      responses:
        "200":
          description: "Successful operation"
        "405":
          description: "Invalid input"

### *the input*  is a dictionary
{ 'number' : <area_code_with_phone_number_string>}

### *the output* is a http response code

### *the function* as it seems is to make a phone call
