### ISSUE TITLE
Implement store endpoints; create store, get_all stores, get_a store, update_a store, delete_a store

### ISSUE THREAD

**Issue by KimBitrus26** [hngi/jl-python-mycustomer#38]
## Complete this section

**What Functionality / Service / Endpoint would you like to add?**
A short statement

**Describe this Functionality / Service / Endpoint**
A clear and concise description of what you want to add.

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature. 

**Slack username**
Please include your slack username here
@Kim 
**Additional context**

## If you're working on an endpoint

- search the **"swagger.yaml"** file in the base dir for the enpoint you're working on, example:  /store/update/{storeId}

- then uncomment the section of the file under that endpoint

- now change operationId of that endpoint to the full qualifier for your function,

  example:  **operationId: "updateStore"  ==> operationId: endpoints.store.update** 
  
  where **"update"** is the function, **"store"** is the file (store.py) and **"endpoints"** is the directory containing that file
  
### OR
  
  if you haven't worked with swagger specifications before and are confused by this, 

- open the issue you want to work on

- comment on the issue with the name of the function, the name of the script you'll open, and the full path relative to the base directory that it'll live

- when I approve/assign the issue to you, I'll comment  with 
            the input your function must take and
            the expected output

**Comment by cAtaman** [comment]
Please add a description for the feature you want to implement  as above

**Comment by austitech** [comment]
This issue will be broken down to create individual issues for each endpoint.
