### ISSUE TITLE
User Endpoints (4 different endpoints)

### ISSUE THREAD

**Issue by aeesha-T** [hngi/jl-python-mycustomer#41]
## Complete this section

**What Functionality / Service / Endpoint would you like to add?**
Retrieve User by ID endpoint
Update User Endpoint
Delete User Endpoint
Create User Endpoint

**Describe this Functionality / Service / Endpoint**
Different endpoints to retrieve user by ID, update the user, delete the user and create the user

**Duplicate prevention**
No duplicates

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature. 

**Slack username**
@aeesha-T

**Additional context**
None

## If you're working on an endpoint

- search the **"swagger.yaml"** file in the base dir for the enpoint you're working on, example:  /store/update/{storeId}

- then uncomment the section of the file under that endpoint

- now change operationId of that endpoint to the full qualifier for your function,

  example:  **operationId: "updateStore"  ==> operationId: endpoints.store.update** 
  
  where **"update"** is the function, **"store"** is the file (store.py) and **"endpoints"** is the directory containing that file
  
### OR
  
  if you haven't worked with swagger specifications before and are confused by this, 

- open the issue you want to work on

- comment on the issue with the name of the function, the name of the script you'll open, and the full path relative to the base directory that it'll live

- when I approve/assign the issue to you, I'll comment  with 
            the input your function must take and
            the expected output

**Comment by austitech** [comment]
Work on a single endpoint and take up another when you are done.

**Comment by aeesha-T** [comment]
Okay. Can I edit this issue to have it focus on one endpoint before it is assigned to me?
