### ISSUE TITLE
Feature: Update User

### ISSUE THREAD

**Issue by austitech** [hngi/jl-python-mycustomer#43]
**Endpoint**
Update User

**Description**
Endpoint to update an existing user record in the database

**Created By**
@austitech 

**Slack Username**
@Austino

**Others**

**Comment by Logan1x** [comment]
is this up for grabs?

**Comment by austitech** [comment]
yes

**Comment by Logan1x** [comment]
Ok then i am interested in working on this.

**Comment by Clashkid155** [comment]
@Logan1x Are you done ? I want to take over.

**Comment by Logan1x** [comment]
I've done the most work, but not able to solve that error. Can you help me with that please. I haven't made any other contribution.

**Comment by Clashkid155** [comment]
Let me check

**Comment by Timmy-id** [comment]
Hey, @Logan1x Have you been able to solve the error?

**Comment by Logan1x** [comment]
Nope any lead from you?

**Comment by Timmy-id** [comment]
Yes, I've a way around it @Logan1x

**Comment by Logan1x** [comment]
Would you please share?

**Comment by Timmy-id** [comment]
![user update](https://user-images.githubusercontent.com/35671277/86239822-eda9b780-bb97-11ea-85f6-d31e73be7228.PNG)

**Comment by Timmy-id** [comment]
@Logan1x

**Comment by Logan1x** [comment]
Cool I'll implement that.

**Comment by Timmy-id** [comment]
Let me know if it works @Logan1x

**Comment by Clashkid155** [comment]
@Timmy-id That code looks familiar 😐

**Comment by Clashkid155** [comment]
And that's not the error. @Logan1x  user telegram username

**Comment by Logan1x** [comment]
its same @Logan1x

**Comment by Clashkid155** [comment]
Okay

**Comment by Timmy-id** [comment]
Have you updated the swagger.yaml file? @Logan1x

**Comment by Logan1x** [comment]
Nope

**Comment by Timmy-id** [comment]
[swagger file.txt](https://github.com/hngi/jl-python-mycustomer/files/4857644/swagger.file.txt)

Go to the update user section and copy and replace with yours in the swagger.yaml file

**Comment by Timmy-id** [comment]
@Logan1x

**Comment by Logan1x** [comment]
Thank you @Timmy-id finally pr'ed again.
