### ISSUE TITLE
Feature: Get User

### ISSUE THREAD

**Issue by austitech** [hngi/jl-python-mycustomer#49]
## Complete this section

**What Functionality / Service / Endpoint would you like to add?**
Get user instance

**Describe this Functionality / Service / Endpoint**
Retrieve a single user instance from the database

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?
Yes

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature. 

**Slack username**
Please include your slack username here

**Additional context**

## If you're working on an endpoint

- search the **"swagger.yaml"** file in the base dir for the enpoint you're working on, example:  /store/update/{storeId}

- then uncomment the section of the file under that endpoint

- now change operationId of that endpoint to the full qualifier for your function,

  example:  **operationId: "updateStore"  ==> operationId: endpoints.store.update** 
  
  where **"update"** is the function, **"store"** is the file (store.py) and **"endpoints"** is the directory containing that file
  
### OR
  
  if you haven't worked with swagger specifications before and are confused by this, 

- open the issue you want to work on

- comment on the issue with the name of the function, the name of the script you'll open, and the full path relative to the base directory that it'll live

- when I approve/assign the issue to you, I'll comment  with 
            the input your function must take and
            the expected output

**Comment by parthpandyappp** [comment]
I'll be glad contributing on this!

**Comment by parthpandyappp** [comment]
I'm about to Complete this, please don't take it back. Almost done with this!
