### ISSUE TITLE
Redirect 127.0.0.1:5207

### ISSUE THREAD

**Issue by chinazaaa** [hngi/jl-python-mycustomer#65]
**Describe the bug**

127.0.0.1:5207 should redirect straight to the docs and not 127.0.0.1:5207/ui

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
@Naza

**Additional context**

**Comment by Clashkid155** [comment]
Already sent pr

**Comment by cAtaman** [comment]
This has been fixed and pr merged
