### ISSUE TITLE
implementing store models

### ISSUE THREAD

**Issue by KimBitrus26** [hngi/jl-python-mycustomer#9]
**What Functionality / Service / Endpoint would you like to add?**
Store model schema

**Describe this Functionality / Service / Endpoint**
Enable ORM access when doing CRUD operations on store records

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?
None

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature. 
    
**Slack username**
@Kim
Please include your slack username here

**Additional context**

**Comment by austitech** [comment]
https://github.com/hngi/sentry-my-customer-backend/blob/develop/models/store.js

Your model must have all the fields and attributes as defined in the above model.

**Comment by KimBitrus26** [comment]
OK noted
